export const English = {
  hint: "US",
  headerLanguage: "Language",
  headerLoading: "Loading",
  headerNoResult: "No results were found",
  homeTitle: "Menu",
  homeTrending: "Trending",
  homeTopRated: "top rated",
  homePopular: "Popular",
  homeNowPlaying: "NOW PLAYING MOVIES",
  homeUpComing: "UPCOMING MOVIES",
  homeTvShows: "TV SHOWS AIRING TODAY",
  homeCurrentlyTv: "CURRENTLY AIRING TV SHOWS",
  exploreScore: "score",
  exploreMiniVote: "Minimum Voted",
  exploreResetBtn: "reset",
  exploreTvTitle: "Tv series",
  exploreMovieTitle: "movie",
  detailNation: "Nation",
  detailEpisodes: "Episodes",
  detailSeasons: "Seasons",
  detailEps: "Eps",
  detailOverview: "Overview",
  detailDuration: "duration",
  detailReadMore: "read More",
  detailWatch: "Watch",
  detailTrailer: "Trailer",
  detailErrorTrailer: "This Tv or Movie don't have trailer!",
  detailSeris: "In the series",
  detailSimilar: "Similar to this",
  detailCharacters: "characters",
  sideBar1: "home",
  sideBar2: "people",
  sideBar3: "explore",
  sideBar4: "history",
  headerSearch: "Search",
  playerCurrentSession: "Current session",
  playerBudget: "budget",
  playerComments: "comments",
  playerCommentsLeft: "You need",
  playerCommentsRight: "to comment",
  login: "Sign in",
  logout: "Sign out",
  signUp: "Sign up",
  peoplePersonalInfo: "Personal Info",
  peopleKnownFor: "Known For",
  peopleGender: "Gender",
  peopleBirthdate: "Birthdate",
  peoplePlaceOfBirth: "Place Of Birth",
  peopleGenderMale: "Male",
  peopleGenderFemale: "Female",
  peopleBiography: "Biography",
  peopleActing: "Acting",
  peopleProduction: "Production",
  peopleAsKnown: "Also Known As",
  peopleReadMore: "Read More",
  peopleReadLess: "Read Less",
  userEditProfile: "Edit profile",
  userChangeAvatar: "change avatar",
  userUpdateInfo: "Update info",
  userUpdatePassword: "Update password",
  userInfo: "User info",
  userPassword: "Password",
  errDontCry: "DON’T CRY",
  errPageNotFound: "Page not found!",
  err404: "It's just a 404 Error!",
  errMess:
    "What you’re looking for may have been misplaced in Long Term Memory.",
  searchResults: "Search Results",
  searchKeyWord: "Key Word",
  person: "person",
  nothingToSee: "Nothing to see",
  home: "Home",
  search: "Search",
  detail: "Detail",
  actor: "Actor",
  history: "History",
  profile: "Profile",
  popularPeople: "Popular people",
  error: "Error",
  notLogin: "You are not logged in",
  imageRequire: "The selected file must be an image",
  someErr: "Something error",
  successUpload: "Upload successfully",
  successUpdate: "Update successfully",
  successSignup: "Sign up successfully",
  name: "Name",
  yourName: "Your name",
  phoneNumber: "Phone number",
  urPhoneNumber: "Your phone number",
  address: "Address",
  urAddress: "Your address",
  birth: "Birth day",
  gender: "gender",
  male: "Male",
  female: "Female",
  genderNull: "Other",
  currentPassword: "Current password",
  urCurrentPassword: "Your current password",
  newPassword: "New password",
  urNewPassword: "Your new password",
  cfPassword: "Comfirm password",
  cfNewPassword: "Comfirm new password",
  currentPwRequire: "The currentPassword field is required",
  currentPwLength: "The current Password is more than 6 characters",
  newPwRequire: "The newPassword field is required",
  newPwLength: "The new Password is more than 6 characters",
  cfPwRequire: "The comfirm Password field is required",
  cfNotCorrect: "Comfirm password is not correct",
  pwRequire: "The Password field is required",
  emailRequire: "The email field is required",
  emailCheck: "This field is email.",
  watchHistory: "Movie viewing history",
  noWatchHistory: "You have no history of watching movies",
  deleteHistory: "Delete history",
  reportProblem: "Report problem",
  account: "account",
  or: "or",
  signInWith: "Sign in with:",
  noAccount: "You don't have account",
  signUpNow: "Sign up now",
  haveAccount: "You have account",
  signInNow: "Sign in now",
  momentSetup: "en-gb",
  sessions: "sessions",
  episodes: "episodes",
};
