export const English = {
  hint: "US",
  headerLanguage: "Language",
  headerLoading: "Loading",
  headerNoResult: "No results were found",
  homeTitle: "Menu",
  homeTrending: "Trending",
  homeTopRated: "top rated",
  homePopular: "Popular",
  homeNowPlaying: "NOW PLAYING MOVIES",
  homeUpComing: "UPCOMING MOVIES",
  homeTvShows: "TV SHOWS AIRING TODAY",
  homeCurrentlyTv: "CURRENTLY AIRING TV SHOWS",
  exploreScore: "score",
  exploreMiniVote: "Minimum Voted",
  exploreResetBtn: "reset",
  exploreTvTitle: "Tv series",
  exploreMovieTitle: "movie",
  detailNation: "Nation",
  detailEpisodes: "Episodes",
  detailSeasons: "Seasons",
  detailEps: "Eps",
  detailOverview: "Overview",
  detailDuration: "duration",
  detailReadMore: "read More",
  detailWatch: "Watch",
  detailTrailer: "Trailer",
  detailSeris: "In the series",
  detailSimilar: "Similar to this",
  detailCharacters: "characters",
  sideBar1: "home",
  sideBar2: "short video",
  sideBar3: "explore",
  sideBar4: "history",
  headerSearch: "search",
  playerCurrentSession: "Current session",
  playerBudget: "budget",
  playerComments: "comments",
  playerCommentsLeft: "You need",
  playerCommentsRight: "to comment",
  login: "login",
  logout: "logout",
};
