export const VietNam = {
  hint: "VN",
  headerLanguage: "Ngôn ngữ",
  headerLoading: "Đang tìm kiếm",
  headerNoResult: "Không tìm thấy kết quả",
  homeTitle: "Menu",
  homeTrending: "xu hướng",
  homeTopRated: "top bình chọn",
  homePopular: "phổ biến",
  homeNowPlaying: "phim đang phát hành",
  homeUpComing: "phim sắp chiếu",
  homeTvShows: "truyền hình hay hôm nay",
  homeCurrentlyTv: "truyền hình hay gần đây",
  exploreScore: "điểm",
  exploreMiniVote: "bình chọn tối thiểu",
  exploreResetBtn: "cài lại",
  exploreTvTitle: "truyền hình dài tập",
  exploreMovieTitle: "phim chiếu rạp",
  detailNation: "Quốc gia",
  detailEpisodes: "Số tập",
  detailSeasons: "Số phần",
  detailEps: "tập",
  detailOverview: "Tổng quát",
  detailDuration: "thời lượng",
  detailReadMore: "xem thêm",
  detailWatch: "Xem phim",
  detailTrailer: "Giới thiệu",
  detailErrorTrailer: "Tv series hoặc Phim này không có trailer!!",
  detailSeris: "Trong bộ truyện",
  detailSimilar: "Phim tương tự",
  detailCharacters: "diễn viên",
  sideBar1: "Trang chủ",
  sideBar2: "Diễn viên",
  sideBar3: "khám phá",
  sideBar4: "lịch sử",
  headerSearch: "tìm kiếm",
  playerCurrentSession: "Phần phim đang phát",
  playerBudget: "Chi phí sản xuất",
  playerComments: "bình luận",
  playerCommentsLeft: "Bạn cần",
  playerCommentsRight: "để bình luận",
  login: "đăng nhập",
  logout: "đăng ký",
  peoplePersonalInfo: "Thông tin cá nhân",
  peopleKnownFor: "Được biết tới",
  peopleGender: "giới tính",
  peopleBirthdate: "ngày sinh",
  peoplePlaceOfBirth: "nơi sinh",
  peopleGenderMale: "nam",
  peopleGenderFemale: "nữ",
  peopleBiography: "tiểu sử",
  peopleActing: "Diễn xuất",
  peopleProduction: "sản xuất",
  peopleAsKnown: "Còn được biết là",
  peopleReadMore: "Đọc thêm",
  peopleReadLess: "đọc ít hơn",
  searchResults: "kết quả tìm kiếm",
  searchKeyWord: "từ khóa",
  person: "nhân vật",
  nothingToSee: "không có gì để xem",
};
