export const VietNam = {
  hint: "VN",
  headerLanguage: "Ngôn ngữ",
  headerLoading: "Đang tìm kiếm",
  headerNoResult: "Không tìm thấy kết quả",
  homeTitle: "Menu",
  homeTrending: "xu hướng",
  homeTopRated: "top bình chọn",
  homePopular: "phổ biến",
  homeNowPlaying: "phim đang phát hành",
  homeUpComing: "phim sắp chiếu",
  homeTvShows: "truyền hình hay hôm nay",
  homeCurrentlyTv: "truyền hình hay gần đây",
  exploreScore: "điểm",
  exploreMiniVote: "bình chọn tối thiểu",
  exploreResetBtn: "cài lại",
  exploreTvTitle: "truyền hình dài tập",
  exploreMovieTitle: "phim chiếu rạp",
  detailNation: "Quốc gia",
  detailEpisodes: "Số tập",
  detailSeasons: "Số phần",
  detailEps: "tập",
  detailOverview: "Tổng quát",
  detailDuration: "thời lượng",
  detailReadMore: "xem thêm",
  detailWatch: "Xem phim",
  detailTrailer: "Giới thiệu",
  detailErrorTrailer: "Tv series hoặc Phim này không có trailer!!",
  detailSeris: "Trong bộ truyện",
  detailSimilar: "Phim tương tự",
  detailCharacters: "diễn viên",
  sideBar1: "Trang chủ",
  sideBar2: "Nghệ sĩ",
  sideBar3: "khám phá",
  sideBar4: "lịch sử",
  headerSearch: "Tìm kiếm",
  playerCurrentSession: "Phần phim đang phát",
  playerBudget: "Chi phí sản xuất",
  playerComments: "bình luận",
  playerCommentsLeft: "Bạn cần",
  playerCommentsRight: "để bình luận",
  login: "Đăng nhập",
  logout: "Đăng xuất",
  signUp: "Đăng ký",
  peoplePersonalInfo: "Thông tin cá nhân",
  peopleKnownFor: "Được biết tới",
  peopleGender: "giới tính",
  peopleBirthdate: "ngày sinh",
  peoplePlaceOfBirth: "nơi sinh",
  peopleGenderMale: "nam",
  peopleGenderFemale: "nữ",
  peopleBiography: "tiểu sử",
  peopleActing: "Diễn xuất",
  peopleProduction: "sản xuất",
  peopleAsKnown: "Còn được biết là",
  peopleReadMore: "Đọc thêm",
  peopleReadLess: "đọc ít hơn",
  userEditProfile: "Chỉnh sửa thông tin",
  userChangeAvatar: "Thay ảnh đại diện",
  userUpdateInfo: "Cập nhật thông tin",
  userUpdatePassword: "Cập nhật mật khẩu",
  userInfo: "Thông tin cá nhân",
  userPassword: "Mật khẩu",
  errDontCry: "Đừng buồn",
  errPageNotFound: "Không tìm thấy trang này!",
  err404: "Lỗi 404!",
  errMess: "Những gì bạn đang tìm kiếm hiện tại xảy ra lỗi,vui lòng thử lại.",
  searchResults: "kết quả tìm kiếm",
  searchKeyWord: "từ khóa",
  person: "nhân vật",
  nothingToSee: "Không có gì để xem",
  home: "Trang chủ",
  search: "Tìm kiếm",
  detail: "Chi tiết",
  actor: "Diễn viên",
  history: "Lịch sử",
  profile: "Trang cá nhân",
  popularPeople: "Người nổi tiếng",
  error: "Lỗi",
  notLogin: "Bạn chưa đăng nhập",
  imageRequire: "File được chọn phải là ảnh",
  someErr: "Có lỗi xảy ra",
  successChange: "Thay đổi thành công",
  successUpdate: "Cập nhật thành công",
  successSignup: "Đăng ký thành công",
  name: "Tên",
  yourName: "Tên của bạn",
  phoneNumber: "Số điện thoại",
  urPhoneNumber: "Số điện thoại của bạn",
  address: "Địa chỉ",
  urAddress: "Địa chỉ của bạn",
  birth: "Ngày sinh",
  gender: "Giới tính",
  male: "Nam",
  female: "Nữ",
  genderNull: "Khác",
  currentPassword: "Mật khẩu hiện tại",
  urCurrentPassword: "Mật khẩu hiện tại của bạn",
  newPassword: "Mật khẩu mới",
  urNewPassword: "Mật khẩu mới của bạn",
  cfPassword: "Xác nhận mật khẩu",
  cfNewPassword: "Xác nhận mật khẩu mới",
  currentPwRequire: "Trường mật khẩu hiện tại không được bỏ trống",
  currentPwLength: "Mật khẩu phải nhiều hơn 6 kí tự",
  newPwRequire: "Trường mật khẩu mới không được bỏ trống",
  newPwLength: "Mật khẩu phải nhiều hơn 6 kí tự",
  cfPwRequire: "Trường xác nhận mật khẩu không được bỏ trống",
  cfNotCorrect: "Xác nhận mật khẩu không đúng",
  pwRequire: "Trường mật khẩu không được bỏ trống",
  emailRequire: "Trường email không được bỏ trống",
  emailCheck: "Trường này phải là email",
  watchHistory: "Lịch sử xem phim",
  noWatchHistory: "Bạn chưa có lịch sử xem phim",
  deleteHistory: "Xóa lịch sử",
  reportProblem: "Báo cáo vấn đề",
  account: "Tài khoản",
  or: "hoặc",
  signInWith: "Đăng nhập bằng:",
  noAccount: "Bạn chưa có tài khoản",
  signUpNow: "Đăng ký ngay",
  haveAccount: "Bạn đã có tài khoản",
  signInNow: "Đăng nhập ngay",
  momentSetup: "vi",
  sessions: "Danh sách phần phim",
  episodes: "Danh sách tập",
};
